//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PimmsInterface.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\VioController")]
        public string sBasePath {
            get {
                return ((string)(this["sBasePath"]));
            }
            set {
                this["sBasePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Camera")]
        public string sCameraFolder {
            get {
                return ((string)(this["sCameraFolder"]));
            }
            set {
                this["sCameraFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Controller")]
        public string sControllerFolder {
            get {
                return ((string)(this["sControllerFolder"]));
            }
            set {
                this["sControllerFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int iNumberOfCameras {
            get {
                return ((int)(this["iNumberOfCameras"]));
            }
            set {
                this["iNumberOfCameras"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int iNumberOfControllers {
            get {
                return ((int)(this["iNumberOfControllers"]));
            }
            set {
                this["iNumberOfControllers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\VioController\\source")]
        public string sSourceFilePath {
            get {
                return ((string)(this["sSourceFilePath"]));
            }
            set {
                this["sSourceFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.231")]
        public string sServerIpAddress {
            get {
                return ((string)(this["sServerIpAddress"]));
            }
            set {
                this["sServerIpAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.86")]
        public string sTriggerIpAddress {
            get {
                return ((string)(this["sTriggerIpAddress"]));
            }
            set {
                this["sTriggerIpAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.31")]
        public string sController1IpAddress {
            get {
                return ((string)(this["sController1IpAddress"]));
            }
            set {
                this["sController1IpAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.32")]
        public string sController2IpAddress {
            get {
                return ((string)(this["sController2IpAddress"]));
            }
            set {
                this["sController2IpAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57343")]
        public int iServerPort {
            get {
                return ((int)(this["iServerPort"]));
            }
            set {
                this["iServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("battery.ini")]
        public string sBatteryIniFile {
            get {
                return ((string)(this["sBatteryIniFile"]));
            }
            set {
                this["sBatteryIniFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("clip0.mpg")]
        public string sVideoFile {
            get {
                return ((string)(this["sVideoFile"]));
            }
            set {
                this["sVideoFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("clip0.inf")]
        public string sVideoInfFile {
            get {
                return ((string)(this["sVideoInfFile"]));
            }
            set {
                this["sVideoInfFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int iNumberOfRows {
            get {
                return ((int)(this["iNumberOfRows"]));
            }
            set {
                this["iNumberOfRows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("57344")]
        public int iListenPort {
            get {
                return ((int)(this["iListenPort"]));
            }
            set {
                this["iListenPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.33")]
        public string sController3IpAddress {
            get {
                return ((string)(this["sController3IpAddress"]));
            }
            set {
                this["sController3IpAddress"] = value;
            }
        }
    }
}
